name: "Build and test Nix package on Ubuntu"

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Test code
        run: nix develop --command cargo test
      - name: Building Nix package
        run: nix build .
