name: "Build legacy Nix package on Ubuntu"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - name: Building Nix package
        run: nix build .
